### ISSUE TITLE
Use versioned sequence identifiers from SeqRepo

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/variant-normalization#34]
The SeqRepo datastore has been updated to use versioned Ensembl identifiers (see https://github.com/biocommons/biocommons.seqrepo/issues/80). VarLex will fail to find protein sequences for users  doing fresh installs / seqrepo pulls.

We should revise VarLex to use versioned identifiers for SeqRepo client queries. We should also build in some QA to identify when an alias is not present in the SeqRepo client (as opposed to when a query is outside of the range of a given sequence).

**Comment by ahwagner** [comment]
Per @acoffman:

> Ah-ha that makes sense. I believe the transcript file we're using has versioned and unversioned columns (if i'm remembering correctly) so just changing which column we import may fix it for now. I was importing the ones without versions because that's what Seqrepo supported at the time
>
> Yeah, so here: https://github.com/GenomicMedLab/varlex/blob/master/varlexapp/data_sources/transcript_mappings.py#L17
> ```protein_transcript = row['Protein stable ID']```

**Comment by korikuzma** [comment]
We now use `protein_transcript = row['Protein stable ID version']` this change can be seen here.
